### ISSUE TITLE
Import error.

### ISSUE THREAD

**Issue by 5amfung** [stevepapa/angular2-autosize#2]
Do you know why I'm getting the error from import ?
Here's how I import it from `node_modules` and others like `angular2` are imported the same way.  

```
import { Autosize } from 'angular2-autosize/angular2-autosize';
```

However, the import is giving me the error.

```
./~/angular2-autosize/angular2-autosize.ts
Module parse failed: /Users/foo/dev/my-app/node_modules/angular2-autosize/angular2-autosize.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import {Autosize} from './src/autosize.directive';
| 
| export * from './src/autosize.directive';
```

**Comment by stevepapa** [comment]
Hi, this looks like it's related to your webpack configuration, usually this error occurs when you haven't enabled a parser for ES6. You may need to add the preset for es2015 to your configuration.

Take a look at this answer, i think you'll find it handy: http://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b

**Comment by chimon2000** [comment]
@stevepapa seems like a common practice for the angular2 team to have a pre-publish/build step that builds the actual output of the npm package.
