### ISSUE TITLE
Cannot find angular2-autosize.js 404 not found

### ISSUE THREAD

**Issue by jcmembrefk** [stevepapa/angular2-autosize#3]
Hello,

Im using angular2-autosize with angular2.
I installed with npm and when i lunch my projet i have this error message : 

Cannot find angular2-autosize.js 404 not found

have you an idea for fix it ?? 

thank you

**Comment by divyekhanna** [comment]
+1

**Comment by quiringk** [comment]
+1

**Comment by quiringk** [comment]
Might need to be updated for release candidate new directory/file structure? autosize.directive.ts is still importing from angular2/core instead of @angular/core. But I still get the 404 when I change it.

**Comment by quiringk** [comment]
got it working after adding it properly in system.config.js and package.json

**Comment by renevall** [comment]
@quiringk how?

**Comment by stevepapa** [comment]
this appears to be resolved, thank you.

**Comment by snstarosciak** [comment]
So I'm actually running into this problem still and I'm running Angular 2.2.1 and Ionic 2.0.0. Any updated fixes to this?

**Comment by sumithasudhakar** [comment]
So I'm actually running into this problem still and I'm running Angular 2.2.1 and Ionic 2.0.0. Any updated fixes to this?
