### ISSUE TITLE
Autosize on binding

### ISSUE THREAD

**Issue by Dyljyn** [stevepapa/angular2-autosize#7]
Instead of **ngOnInit**, I have used **ngAfterContentChecked**.

This way it will start resizing after the bindings are done. Maybe to have this in the original code?

**Comment by sinedsem** [comment]
+1
BTW, It's already done by @Pietrex 
https://github.com/Pietrex/angular2-autosize

**Comment by Akuryou** [comment]
The changes made by @Pietrex work for me.
@Pietrex how about creating a PR?

**Comment by stevepapa** [comment]
this is resolved, thank you.
